[[override]]
  name = "k8s.io/client-go"
  version = "7.0.0"

[[constraint]]
  name = "k8s.io/kubectl"
  branch = "master"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "release-1.10"

# vendor/k8s.io/client-go/plugin/pkg/client/auth/azure/azure.go:300:8: cannot use spt.Token (type func() adal.Token) as type adal.Token in field value
[[override]]
  name = "github.com/Azure/go-autorest"
  version = "v9.9.0"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
