[[override]]
  name = "k8s.io/client-go"
  version = "8.0.0"

[[constraint]]
  name = "k8s.io/kubectl"
  branch = "master"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "release-1.11"

# vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go:104:16: unknown field 'CaseSensitive' in struct literal of type jsoniter.Config
[[override]]
  name = "github.com/json-iterator/go"
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
