[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.14.0"

[[constraint]]
  name = "k8s.io/cli-runtime"
  branch = "release-1.14"

[[constraint]]
  name = "k8s.io/kubernetes"
  branch = "release-1.14"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "release-1.14"

[[override]]
  name = "github.com/Azure/go-autorest"
  version = "v11.1.0"

[[override]]
  name = "github.com/golang/protobuf"
  version = "v1.3.1"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
