[[override]]
  name = "k8s.io/client-go"
  version = "9.0.0"

[[constraint]]
  name = "k8s.io/cli-runtime"
  branch = "release-1.12"

[[constraint]]
  name = "k8s.io/kubernetes"
  branch = "release-1.12"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "release-1.12"

# cannot use ASCIIRenderer literal (type *ASCIIRenderer) as type blackfriday.Renderer in assignment:
[[override]]
  name = "github.com/russross/blackfriday"
  revision = "300106c228d52c8941d4b3de6054a6062a86dda3"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
