name: CI

on:
  push:
    branches: [master]
    tags: ["v*"]
    paths-ignore: ['**.md']
  pull_request:
    types: [opened, synchronize]
    paths-ignore: ['**.md']

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: "~1.15.2"
    - name: Ensure go.mod is already tidied
      run: go mod tidy && git diff -s --exit-code go.sum
    - run: make vet fmt build dist
    - run: ./hack/install-krew.sh
    - run: make test-dist
    - name: Create a new release
      if: contains(github.ref, 'tags')
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload binaries to the new release
      if: contains(github.ref, 'tags')
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: _dist/*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
  create-pr:
    needs: [run]
    if: contains(github.ref, 'tags')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: kubernetes-sigs/krew-index
    - run: echo ::set-env name=GIT_TAG::${GITHUB_REF##*/}
    - name: Download the released krew plugin manifest file
      run: |
        curl -sLo plugins/view-serviceaccount-kubeconfig.yaml https://github.com/superbrothers/kubectl-view-serviceaccount-kubeconfig-plugin/releases/download/${{ env.GIT_TAG }}/view-serviceaccount-kubeconfig.yaml
        git --no-pager diff
    - uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GH_PAT }}
        committer: Kazuki Suda <230185+superbrothers@users.noreply.github.com>
        author: Kazuki Suda <230185+superbrothers@users.noreply.github.com>
        commit-message: Bump the version of view-serviceaccount-kubeconfig to ${{ env.GIT_TAG }}
        title: Bump the version of view-serviceaccount-kubeconfig to ${{ env.GIT_TAG }}
        body: This PR bumps up the version of view-serviceaccount-kubeconfig to ${{ env.GIT_TAG }}.
        branch: view-serviceaccount-kubeconfig-${{ env.GIT_TAG }}
        push-to-fork: superbrothers/krew-index
